---
title: "Untitled"
author: "Gabriella Martinez"
date: "10/5/2022"
output: html_document
---

^[https://github.com/tidyverse/dplyr/issues/5214]
```{r}
# remove.packages("rlang")
# install.packages("rlang")
```



```{r message=FALSE, warning=FALSE}
library(dplyr)
library(leaflet)
library(tigris)
library(plotly)
library(shiny)
library(shinythemes)
library(rsconnect)
library(sf)
```

```{r message=FALSE, warning=FALSE}
df <- read.csv("https://raw.githubusercontent.com/charleyferrari/CUNY_DATA_608/master/module3/data/cleaned-cdc-mortality-1999-2010-2.csv")

names(df) <- lapply(names(df), tolower)
```

```{r message=FALSE, warning=FALSE}
str(df)

unique(df$icd.chapter)

#df$ICD.Chapter <- as.factor(df$ICD.Chapter)
```

```{r message=FALSE, warning=FALSE}
#load in shapefile
states <- tigris::states(cb=T)

#change column name on shapefile for left join with death data
states <- states %>% rename("state" = "STUSPS")
```

^[https://stackoverflow.com/questions/73181511/shapefile-warnings-in-r]
```{r message=FALSE, warning=FALSE}
st_crs(states)$epsg

states <- st_transform(states, 4326)
```


```{r message=FALSE, warning=FALSE}
#merge
#states_merged <- df %>% left_join(states, by="State")

#need to use geo_join in order to get sf type dataframe for leaflet
states_merged <- geo_join(data_frame=df, spatial_data= states, by_df= "state", by_sp= "state", by = NULL, how = "inner")

#remove NA
states_merged <- subset(states_merged, !is.na(crude.rate))
```

# Create a Static Map keeping `year` and `icd.chapter` constant
```{r message=FALSE, warning=FALSE}
states_merged_filtered <- filter(states_merged, year == 2010 & icd.chapter == 'Mental and behavioural disorders')

# #create color palette based on range of Crude.Rate
pal <- colorNumeric("Reds", domain=states_merged_filtered$crude.rate)

# Setting up the pop up text
popup_sb <- with(states_merged_filtered,
                 paste(NAME, '<br>',
                       "Crude Rate: ", crude.rate ,'<br>',
                       "Deaths: ", deaths, '<br>',"Population", population))
```

^[https://learn.r-journalism.com/en/mapping/census_maps/census-maps/]
```{r}
# Mapping it with the new tiles CartoDB.Positron
leaflet() %>%
  addProviderTiles("CartoDB.Positron") %>%
  setView(-98.483330, 38.712046, zoom = 4) %>%
  addPolygons(data = states_merged_filtered,
              fillColor = ~pal(states_merged_filtered$crude.rate),
              fillOpacity = 0.7,
              weight = 0.2,
              smoothFactor = 0.2,
              popup = ~popup_sb) %>%
  addLegend(pal = pal,
            values = states_merged_filtered$crude.rate,
            position = "bottomright",
            title = "Crude Rate")
```



^[https://stackoverflow.com/questions/57030746/shiny-leaflet-reactive-function-not-working]
This is what actually helped me fix it: ^[https://stackoverflow.com/questions/17002160/shiny-tutorial-error-in-r]
```{r}
#shiny app UI

#'Examining Causes of Death Across United States from 1999-2010'
#'
#'fluidRow(
  #   column(9, "Examining Causes of Death Across the US from 1999-2010"), 
  #   column(9, "Death rate per 100,000 persons")
  # )

ui <- fluidPage(
    titlePanel(
               "Examining Causes of Death Across the US from 1999-2010"
               ),
    sidebarLayout(
        sidebarPanel(
           selectInput(
                inputId = 'year', 
                label = 'Year:', 
                choices = unique(states_merged$year),
                selected = 2010),
            selectInput(
                inputId = 'cause', 
                label = 'Cause of Death:', 
                choices = unique(states_merged$icd.chapter),
                selected = "Certain infectious and parasitic diseases"),
                ),
        mainPanel(
           leafletOutput(outputId = 'map', height = 800)
            )
    )
)

#shiny app server
server <- shinyServer(function(input, output, session){
    map_data <- reactive({
      filter(states_merged, year == input$year & icd.chapter == input$cause)
      })

    # #create color palette based on range of Crude.Rate
    #   pal <- colorNumeric("Reds", domain=map_data()$crude.rate)
    # #Setting up the pop up text
    #   popup_sb <- with(map_data(), 
    #              paste(NAME, '<br>',
    #                    "Crude Rate: ", crude.rate ,'<br>',
    #                    "Deaths: ", deaths, '<br>',
    #                    "Population", population))
    output$map <- renderLeaflet({
     #create color palette based on range of Crude.Rate
      pal <- colorNumeric("Reds", domain=map_data()$crude.rate)
     #Setting up the pop up text
      popup_sb <- with(map_data(), 
                 paste(NAME, '<br>',
                       "Year: ", year, '<br>',
                       "Crude Rate: ", crude.rate ,'<br>',
                       "Deaths: ", deaths, '<br>',
                       "Population: ", population))
      #create map  
        map_data() %>% 
        leaflet() %>%
        addProviderTiles("CartoDB.Positron")%>%
        addControl(title, position = "topleft", className="map-title") %>%
        setView(-98.483330, 38.712046, zoom = 4) %>% 
        addPolygons( 
              fillColor = ~pal(map_data()$crude.rate), #reference map_data() 
              fillOpacity = 0.7, 
              weight = 0.2, 
              smoothFactor = 0.2, 
              popup = ~popup_sb) %>%
        addLegend(pal = pal, 
            values = map_data()$crude.rate, #reference map_data() 
            position = "bottomright", 
            title = "Deaths per 100,000 persons")
        
    }
    )
})

shinyApp(ui = ui, server = server)
deployApp()
```

```{r}
# map_data <- reactive({filter(states_merged, 
#                               year == 2010 & icd.chapter == input$cause)})
```

